const Controller = require('./controllers')

exports.controller = {
    home: Controller.HomeController.home,
    signup: Controller.AuthController.signup,
    confirmCode: Controller.AuthController.confirmCode,
    setPassword: Controller.AuthController.setPassword,
    setPin: Controller.AuthController.setPin,
    setUsername: Controller.AuthController.setUsername,
    signIn: Controller.AuthController.signIn,
    dashboard: Controller.DashboardController.dashboard,
    makePayment: Controller.FundsController.makePayment,
    verifyPayment: Controller.FundsController.verifyTransaction,
    webhook: Controller.WebhookController.webhook,
    transferFunds: Controller.TransferController.transferFunds,
    pendingRequests: Controller.RequestController.getPendingRequests,
    acceptedRequests: Controller.RequestController.getAcceptedRequests,
    cancelRequest: Controller.RequestController.cancelRequests,
    createRequest: Controller.RequestController.createRequest,
    markRequest: Controller.RequestController.markRequests,
    createStatus: Controller.StatusController.createStatus,
    findStatus: Controller.StatusController.findStatus,
    resendCode: Controller.AuthController.resendCode,
    getTransactions: Controller.TransactionsController.transactions,
    docs: Controller.HomeController.docs,
    users: Controller.UserController.getUser,
    getAccount: Controller.AccountController.getAccount,
    withdraw: Controller.WithdrawalController.withdrawFund,
    getBalance: Controller.BalanceController.getBalance,
    getRequestStatus: Controller.RequestController.getRequestStatus
}